complete -xc ya -a "disowned" -d "Display list of disowned files"
complete -xc ya -a "in" -d "yaourt -S; Install specific package(s) from the repositories"
complete -xc ya -a "ins" -d "yaourt -S; Display list of disowned files"
complete -xc ya -a "list" -d "yaourt -Qe;	List installed packages, even those installed from AUR (they're tagged as \"local\")"
complete -xc ya -a "loc" -d "yaourt -Qi;	Display information about a given package in the local database"
complete -xc ya -a "locs" -d "yaourt -Qs;	Search for package(s) in the local database"
complete -xc ya -a "upd" -d "yaourt -Sy;	Update and refresh the local package database against repositories"
complete -xc ya -a "upg" -d "yaourt -Syua;	Synchronize with repositories before upgrading packages (AUR packages too) that are out of date on the local system"
complete -xc ya -a "reps" -d "yaourt -Ss;	Search for package(s) in the repositories"
