complete -c yadisowned -d "Display list of disowned files"
complete -c yain -d "yaourt -S; Install specific package(s) from the repositories"
complete -c yains -d "yaourt -S; Display list of disowned files"
complete -c yalist -d "yaourt -Qe;	List installed packages, even those installed from AUR (they're tagged as \"local\")"
complete -c yaloc -d "yaourt -Qi;	Display information about a given package in the local database"
complete -c yalocs -d "yaourt -Qs;	Search for package(s) in the local database"
complete -c yaupd -d "yaourt -Sy;	Update and refresh the local package database against repositories"
complete -c yaupg -d "yaourt -Syua;	Synchronize with repositories before upgrading packages (AUR packages too) that are out of date on the local system"
complete -c yareps -d "yaourt -Ss;	Search for package(s) in the repositories"
